defaults:
  - _self_
  - data: cifar100
  - model: cifar100/msp
  - eval: ood_cifar100


device: 0
  # training:
  # 
  #   n_sample_predict: 500
  #   n_init: 20
  #   reset_inducing_points_every: 5
  #   n_repeats: 5
  #   random_init_data: false
  #   n_active: 30
  #   n_augdata: 1
  # 
  #   acq_function: Uncertainty_Entropy # BALD, Uncertainty_Max
  #   max_acq: 0.65

directories:
  base: .
  data: ${directories.base}/datasets
  results_base: ${directories.base}/results/${data.name}_${model.name}

logger:
  _target_: trainers.logger.BaseLogger

run: dev  # override this for each run name

hydra:
  job:
    config:
      override_dirname:  # used for determining folder name in sweep mode
        exclude_keys:  # exclude these arguments in sweep mode
          - data
          - run 
  job_logging:
    handlers:
      file:
        filename: ${hydra:runtime.output_dir}/run.log
  run:
    dir: ${directories.results_base}/${run} #/${now:%Y-%m-%d-%H-%M-%S}    
  sweep:
    dir: ${hydra.run.dir}
    subdir: ${hydra.job.override_dirname}  
